apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: nginx
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/part-of: nginx
    app.kubernetes.io/version: 1.21.0
  name: nginx-config
data:
  site.conf.template: |
      server {
        charset utf-8;
        listen ${PORT} ;
        location / {
          add_header Content-Type text/html;

          access_log off;
          return 200 '<html><body><h1>nginx with exporter on $hostname\n</h1></body></html>';
        }
        location /stub_status {
          stub_status on;
        }
      }
